## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
# Ans ==
# Yes, there is a difference in the data types of the list_ and array_list variables. The list_ variable is a Python list, while the array_list variable is a NumPy array.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [2]:
# Ans==
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [3]:
# Ans ==

#Yes, there will be a difference in the data types of the elements present in list_ and array_list due to the dtype=int parameter specified when creating the NumPy array. This parameter enforces the data type of the elements in the resulting array to be integers.

#Here's the code to print the data types of each element in both list_ and the modified array_list:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in modified array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in modified array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
## Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
shape_of_array = num_array.shape

# (ii) Size
size_of_array = num_array.size

# Display the results
print("Shape of the array:", shape_of_array)
print("Size of the array:", size_of_array)


Shape of the array: (2, 3)
Size of the array: 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
# Create a 3x3 matrix of zeros
zero_array = np.zeros((3, 3))

# Display the result
print("Numpy array of 3x3 matrix containing zeros:")
print(zero_array)


Numpy array of 3x3 matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Display the result
print("Identity matrix of shape (5, 5):")
print(identity_matrix)


Identity matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
